name: Another Workflow

on:
  workflow_run:
    workflows: ["Trigger Workflow"]
    types:
      - completed

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run the Another Workflow
        run: |
          echo "Running another workflow"
          # Add steps or commands for the triggered workflow
