name: Reusable

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: saksham0197/Thank-You-Action-JS/blob/main/.github/workflows/test.yml@main
    with:
      username: saksham
    secrets:
      token: ${{ secrets.saksham }}
