name: Trigger Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Another Workflow
        uses: actions/checkout@v2

      - name: Trigger Workflow
        run: |
          echo "Running another workflow"
          # You can perform any necessary setup or commands here
